name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main # Run pipeline on pushes to 'main'
  pull_request:
    branches:
      - main # Run pipeline on PRs to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy via SSH (example to a server)
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ 13.232.180.161 }}
          username: ${{ ubuntu }}
          key: ${{ CICDDJANGO }}
          script: |
            cd /home/ubuntu/Tests/Production
            git pull origin main
            source django_env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            systemctl restart Production.service
